# Generated by Django 3.2.6 on 2021-08-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.UUIDField(default='uuid.uuid4', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('nacimiento_fecha', models.DateField()),
                ('documento_numero', models.CharField(max_length=20)),
                ('documento_tipo', models.CharField(choices=[('DNI', 'Documento de Identidad'), ('CI', 'Cedula de Identidad'), ('LE', 'Libreta da Enrolamiento'), ('LC', 'Libreta Civica')], default='DNI', max_length=3)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=2)),
                ('direccion', models.CharField(max_length=256)),
                ('localidad', models.CharField(max_length=128)),
                ('obra_social', models.CharField(max_length=128)),
                ('plan', models.CharField(max_length=128)),
                ('afiliado', models.CharField(max_length=128)),
                ('telefono_linea', models.CharField(max_length=12)),
                ('telefono_celular', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=128)),
                ('profesion', models.CharField(max_length=128)),
                ('referente', models.CharField(max_length=128)),
            ],
        ),
    ]
